#ifndef _PORTS_H_
#define _PORTS_H_

#include "config.h"

/* Automated pin/port/ddr defines */
#define GLUE(A,B) A##B
#define GLUE3(A,B,C) A##B##C

#define PORT(x) GLUE(PORT, x)
#define DDR(x) GLUE(DDR, x)
#define PIN(x) GLUE(PIN, x)
#define PINNUM(x,y) GLUE3(PORT, x, y)


#define TLC_VPRG_PORT 	PORT(TLC_VPRG_PORT_LETTER)
#define TLC_VPRG_DDR  	DDR(TLC_VPRG_PORT_LETTER)
#define TLC_VPRG_PIN  	DDR(TLC_VPRG_PORT_LETTER)
#define TLC_VPRG		PINNUM(TLC_VPRG_PORT_LETTER,TLC_VPRG_PORT_NUMBER)

#define TLC_SIN_PORT 	PORT(TLC_SIN_PORT_LETTER)
#define TLC_SIN_DDR  	DDR(TLC_SIN_PORT_LETTER)
#define TLC_SIN_PIN  	DDR(TLC_SIN_PORT_LETTER)
#define TLC_SIN			PINNUM(TLC_SIN_PORT_LETTER,TLC_SIN_PORT_NUMBER)

#define TLC_SCLK_PORT 	PORT(TLC_SCLK_PORT_LETTER)
#define TLC_SCLK_DDR  	DDR(TLC_SCLK_PORT_LETTER)
#define TLC_SCLK_PIN  	DDR(TLC_SCLK_PORT_LETTER)
#define TLC_SCLK		PINNUM(TLC_SCLK_PORT_LETTER,TLC_SCLK_PORT_NUMBER)

#define TLC_XLAT_PORT 	PORT(TLC_XLAT_PORT_LETTER)
#define TLC_XLAT_DDR  	DDR(TLC_XLAT_PORT_LETTER)
#define TLC_XLAT_PIN  	DDR(TLC_XLAT_PORT_LETTER)
#define TLC_XLAT		PINNUM(TLC_XLAT_PORT_LETTER,TLC_XLAT_PORT_NUMBER)

#define TLC_BLANK_PORT 	PORT(TLC_BLANK_PORT_LETTER)
#define TLC_BLANK_DDR  	DDR(TLC_BLANK_PORT_LETTER)
#define TLC_BLANK_PIN  	DDR(TLC_BLANK_PORT_LETTER)
#define TLC_BLANK		PINNUM(TLC_BLANK_PORT_LETTER,TLC_BLANK_PORT_NUMBER)

#define TLC_GSCLK_PORT 	PORT(TLC_GSCLK_PORT_LETTER)
#define TLC_GSCLK_DDR  	DDR(TLC_GSCLK_PORT_LETTER)
#define TLC_GSCLK_PIN  	DDR(TLC_GSCLK_PORT_LETTER)
#define TLC_GSCLK		PINNUM(TLC_GSCLK_PORT_LETTER,TLC_GSCLK_PORT_NUMBER)

#define TLC_XERR_PORT 	PORT(TLC_XERR_PORT_LETTER)
#define TLC_XERR_DDR  	DDR(TLC_XERR_PORT_LETTER)
#define TLC_XERR_PIN  	DDR(TLC_XERR_PORT_LETTER)
#define TLC_XERR		PINNUM(TLC_XERR_PORT_LETTER,TLC_XERR_PORT_NUMBER)

#define SHIFT_REG_CP_PORT 	PORT(SHIFT_REG_CP_PORT_LETTER)
#define SHIFT_REG_CP_DDR  	DDR(SHIFT_REG_CP_PORT_LETTER)
#define SHIFT_REG_CP_PIN  	DDR(SHIFT_REG_CP_PORT_LETTER)
#define SHIFT_REG_CP		PINNUM(SHIFT_REG_CP_PORT_LETTER,SHIFT_REG_CP_PORT_NUMBER)

#define SHIFT_REG_MR_PORT 	PORT(SHIFT_REG_MR_PORT_LETTER)
#define SHIFT_REG_MR_DDR  	DDR(SHIFT_REG_MR_PORT_LETTER)
#define SHIFT_REG_MR_PIN  	DDR(SHIFT_REG_MR_PORT_LETTER)
#define SHIFT_REG_MR		PINNUM(SHIFT_REG_MR_PORT_LETTER,SHIFT_REG_MR_PORT_NUMBER)

#define SHIFT_REG_SIN_PORT 	PORT(SHIFT_REG_SIN_PORT_LETTER) 
#define SHIFT_REG_SIN_DDR  	DDR(SHIFT_REG_SIN_PORT_LETTER)
#define SHIFT_REG_SIN_PIN  	DDR(SHIFT_REG_SIN_PORT_LETTER)
#define SHIFT_REG_SIN		PINNUM(SHIFT_REG_SIN_PORT_LETTER,SHIFT_REG_SIN_PORT_NUMBER)


#endif
